import {Rule} from 'eslint';

import {getMessagesExpression} from './handlers/messages-expression';
import {BaseRuleOptions, RuleOptions} from './types';

const DEFAULT_MEMBER_EXPRESSIONS: RuleOptions['memberExpressions'] = [
    {member: 'intl', property: 'createMessages'},
];
const DEFAULT_CALL_EXPRESSIONS: RuleOptions['callExpressions'] = ['declareMessages'];
const DEFAULT_IDENTIFIER_NAME = 'id';

export const rule: Rule.RuleModule = {
    meta: {
        fixable: 'code',
        docs: {
            description: 'Add autogenerated message id',
        },
        schema: [
            {
                type: 'object',
                properties: {
                    memberExpressions: {type: 'array'},
                    callExpressions: {type: 'array'},
                    idName: {type: 'string'},
                    namespaceMatchers: {type: 'array'},
                    validateId: {type: 'boolean'},
                },
            },
        ],
    },

    create(context: Rule.RuleContext) {
        const {
            memberExpressions = DEFAULT_MEMBER_EXPRESSIONS,
            callExpressions = DEFAULT_CALL_EXPRESSIONS,
            idName = DEFAULT_IDENTIFIER_NAME,
            namespaceMatchers,
            generateId,
            maxValidLength,
            invalidCharsPattern,
            invalidCharsReplacement,
            invalidCharsReplacer,
            validateId,
        }: RuleOptions = context.options[0] || {};

        const baseParameters: BaseRuleOptions = {
            generateId,
            namespaceMatchers,
            context,
            idName,
            maxValidLength,
            invalidCharsPattern,
            invalidCharsReplacement,
            invalidCharsReplacer,
            validateId,
        };

        const handler = getMessagesExpression({
            ...baseParameters,
            memberExpressions: memberExpressions ?? [],
            callExpressions: callExpressions ?? [],
        });

        return {
            ...(memberExpressions?.length ? {MemberExpression: handler} : {}),
            ...(callExpressions?.length ? {CallExpression: handler} : {}),
        };
    },
};
