import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
// Удалено: глобальный импорт CSS библиотеки. Проверяем автоподключение
import '../styles/globals.scss';

import type {Metadata} from 'next';

import {App} from '../components/App';
import {DEFAULT_BODY_CLASSNAME} from '../components/Wrapper';

export const metadata: Metadata = {
    title: 'Gravity UI – Next.js App Example',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            </head>
            <body className={DEFAULT_BODY_CLASSNAME}>
                <App>{children}</App>
            </body>
        </html>
    );
}
