import {
    AntennaSignal,
    Bell,
    BookOpen,
    Bucket,
    ChartColumn,
    ChartLine,
    ChartPie,
    Cloud,
    CreditCard,
    Database,
    FileText,
    Gear,
    HardDrive,
    House,
    Key,
    LayoutHeaderCellsLarge,
    ListTimeline,
    Person,
    Persons,
    Plus,
    Route,
    ShieldCheck,
    ShieldKeyhole,
    Sliders,
    Terminal,
} from '@gravity-ui/icons';

import type {MenuGroup} from '../../types';
import type {AsideHeaderItem, AsideHeaderProps} from '../types';

export const fullNavigationMenuGroups: MenuGroup[] = [
    {id: 'analytics', title: 'Analytics', icon: ChartColumn, popupTitle: 'Analytics'},
    {id: 'monitoring', title: 'Monitoring', icon: Cloud, popupTitle: 'Monitoring'},
    {id: 'storage', title: 'Storage', icon: Database, popupTitle: 'Storage'},
    {id: 'security', title: 'Security', icon: ShieldKeyhole, popupTitle: 'Security'},
    {id: 'settings', title: 'Settings', icon: Gear, popupTitle: 'Settings'},
];

/** Keep one expanded group visible while making the remaining group headers easy to inspect. */
export const fullNavigationCollapsedGroupIds: AsideHeaderProps['defaultCollapsedMenuGroupIds'] =
    Object.fromEntries(fullNavigationMenuGroups.slice(1).map((group) => [group.id, true]));

export const fullNavigationMenuItems: AsideHeaderItem[] = [
    {
        id: 'create',
        title: 'Create',
        icon: Plus,
        type: 'action',
        afterMoreButton: true,
    },
    {id: 'home', title: 'Home', icon: House, category: 'General'},
    {
        id: 'analytics-overview',
        title: 'Overview',
        icon: ChartPie,
        groupId: 'analytics',
        category: 'Analytics',
    },
    {
        id: 'analytics-reports',
        title: 'Reports',
        icon: FileText,
        groupId: 'analytics',
        category: 'Analytics',
    },
    {
        id: 'analytics-dashboards',
        title: 'Weekly operational performance',
        titleLines: 2,
        icon: LayoutHeaderCellsLarge,
        groupId: 'analytics',
        category: 'Analytics',
    },
    {
        id: 'analytics-metrics',
        title: 'Metrics',
        icon: ChartLine,
        groupId: 'analytics',
        category: 'Analytics',
    },
    {
        id: 'monitoring-alerts',
        title: 'Alerts',
        icon: Bell,
        groupId: 'monitoring',
        category: 'Monitoring',
    },
    {
        id: 'monitoring-logs',
        title: 'Logs',
        icon: Terminal,
        groupId: 'monitoring',
        category: 'Monitoring',
    },
    {
        id: 'monitoring-traces',
        title: 'Traces',
        icon: Route,
        groupId: 'monitoring',
        category: 'Monitoring',
    },
    {
        id: 'monitoring-uptime',
        title: 'Uptime',
        icon: AntennaSignal,
        groupId: 'monitoring',
        category: 'Monitoring',
    },
    {
        id: 'storage-buckets',
        title: 'Buckets',
        icon: Bucket,
        groupId: 'storage',
        category: 'Storage',
    },
    {
        id: 'storage-databases',
        title: 'Databases',
        icon: Database,
        groupId: 'storage',
        category: 'Storage',
    },
    {
        id: 'storage-volumes',
        title: 'Volumes',
        icon: HardDrive,
        groupId: 'storage',
        category: 'Storage',
    },
    {
        id: 'security-access',
        title: 'Access keys',
        icon: Key,
        groupId: 'security',
        category: 'Security',
    },
    {
        id: 'security-roles',
        title: 'Roles',
        icon: Persons,
        groupId: 'security',
        category: 'Security',
    },
    {
        id: 'security-audit',
        title: 'Audit log',
        icon: ListTimeline,
        groupId: 'security',
        category: 'Security',
    },
    {
        id: 'security-policies',
        title: 'Policies',
        icon: ShieldCheck,
        groupId: 'security',
        category: 'Security',
    },
    {
        id: 'general-settings',
        title: 'General',
        icon: Sliders,
        groupId: 'settings',
        category: 'Settings',
    },
    {
        id: 'user-settings',
        title: 'Users',
        icon: Person,
        groupId: 'settings',
        category: 'Settings',
    },
    {
        id: 'billing-settings',
        title: 'Billing',
        icon: CreditCard,
        groupId: 'settings',
        category: 'Settings',
    },
    {id: 'help', title: 'Help', icon: BookOpen, category: 'General'},
];
