# This workflow is used to publish the packages to npm.
# It runs automatically after a release PR is merged, or can be triggered manually.

name: Publish

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
       contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    permissions: write-all

    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}

      - name: Print Environment Info
        run: pnpm exec nx report
        shell: bash

      - name: Build packages
        run: pnpm exec nx run-many --target=build --all
        shell: bash

      - name: Publish packages
        run: pnpm exec nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
